services:
  app:
    build: .
    environment:
      - DATABASE_URL=postgresql+psycopg2://postgres:postgres@db:5432/kyc
    ports: ["8000:8000"]
    depends_on: [db]
  db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: kyc
    ports: ["5432:5432"]
    volumes: [pgdata:/var/lib/postgresql/data]
volumes:
  pgdata:
